### ISSUE TITLE
THANK YOU!

### ISSUE THREAD

**Issue by luc-ass** [bbreukelen/node-rainbird#1]
Thank you so much for building this! I was planing to build a Homebridge plugin for Rain Bird Systems and you saved me so much headache! Again, thank you! I will make my repo public as soon as it runs more or less stable.

**Comment by bbreukelen** [comment]
Hey Lucas,

So happy to hear that it is useful to you!
I found the Rainbird software to be quite limited when it comes to
responding to weather etc, so now I'm making my own decisions when and for
how long irrigate.
What are you using it for?

Bo

**Comment by luc-ass** [comment]
Na main target is to delay mowing the lawn if irrigation is active. Also this way I can use my sprinklers as an intrusion prevention ;)

**Comment by bbreukelen** [comment]
Ah, right.
I do the same thing with my Automower. I have an old one, but built WiFi
into it and I also tell it to go home when irrigation starts.
Good luck!

Bo

**Comment by jcmurty** [comment]
> Thank you so much for building this! I was planing to build a Homebridge plugin for Rain Bird Systems and you saved me so much headache! Again, thank you! I will make my repo public as soon as it runs more or less stable.

any chance you wrote that plugin? my rainbird irrigation system is being installed as I type :-)

**Comment by luc-ass** [comment]
Sorry, the System is at my parents house and some shitty thing keeps me from going there ;)

I would gladly help testing as soon as things ease up a little...

**Comment by amcdnl** [comment]
@luc-ass @jcmurty - either of you build a homebridge rainbird integration yet?

**Comment by ithatcher123** [comment]
I also would love this. 
I need to automate some things into my home regarding railbird.

**Comment by itml-eu** [comment]
Would like to see as well. If no one will build this maybe I will find some time to start playing with it.
