### ISSUE TITLE
Start irrigation?

### ISSUE THREAD

**Issue by arjan127** [bbreukelen/node-rainbird#2]
Hey, firstly thanks a lot for this package. It's a life saver.

I noticed there's a stopIrrigation method, but afterwards there appears to be no way to start irrigation anymore? There's no startIrrigation method?

**Comment by bbreukelen** [comment]
Hi,

Good to hear that you like it.
Did you try startZone?
That's basically the opposite of stopIrriagtion

**Comment by arjan127** [comment]
Thanks Bo, that makes sense! Keep up the good work 👍
