### ISSUE TITLE
Add support for remaining commands

### ISSUE THREAD

**Issue by mantorok1** [bbreukelen/node-rainbird#6]
Hi @bbreukelen,

Thanks for the excellent work you've done on this nodejs library. I'm thinking of using it to write a Rainbird Homebridge plugin but I noticed that some commands haven't yet been exposed. In particular:

- CommandSupportRequest
- WaterBudgetRequest
- ZonesSeasonalAdjustFactorRequest
- AdvanceStationRequest
- CurrentControllerStateSet
- ControllerEventTimestampRequest
- StackManuallyRunStationRequest
- CombinedControllerStateRequest

Could you please update the library to add support for the above?

Regards,
@mantorok1

**Comment by bBsS4** [comment]
Thank you thank you thank you please this would be amazing don't give up! Could I suggest you look at the Orbit B-Hyve homebridge integration GUI if you need any inspiration? Please let me know if I can help - not super experienced but would love to get involved if it helps this move forward.

**Comment by bbreukelen** [comment]
Hi @mantorok1,

I didn't really see the added value of adding these commands and I don't have the time right now to add them.
Maybe someone wants to contribute and do a pull request?

Cheers,

Bo

**Comment by mantorok1** [comment]
@bbreukelen No worries. I'm thinking of taking a different approach with the Homebridge plugin anyway but thanks for the work you've done. It's helped me gain an understanding of the RainBird's API.

@bBsS4 Thanks for the encouragement and suggestion. I'm hoping to make a start on the plugin soon. I've written a couple of others already so I think this one shouldn't been too difficult.

**Comment by donavanbecker** [comment]
@mantorok1, do you need help with the plugin? also I would be willing to test.

**Comment by mantorok1** [comment]
@donavanbecker I've made a start on the plugin so I'll see how I go. If I need help I'll let you know but would be great if you could test when its ready.

**Comment by donavanbecker** [comment]
@mantorok1, not sure how far you are. But this is what I have so far. Will know more once I get it connected to a system.

https://github.com/donavanbecker/homebridge-rainbird. - beta branch
